#!/usr/bin/env bash

# Forked pranklock by vhash and zeub13
# See https://github.com/RealOrangeOne/pranklock
# Prank your firend by showing a meme when touching computer while locked
# and capture and save both photo and video at this time.

# Escape key used to exit lockscreen whitout been pranked
ESCAPE_KEY=9

TEMP_FILE_PHOTO=$(mktemp -t "XXXXXXXXXX.png")
MEME_FILE="/opt/pranklockng/assets/you_got_pranked_yoda.png"

screensize=$(xdpyinfo | grep -i dimensions: | sed 's/[^0-9]*pixels.*(.*).*//' | sed 's/[^0-9x]*//')
grimshot save output $TEMP_FILE_PHOTO
swaylock -i "$TEMP_FILE_PHOTO" &

key=0
while read -r line
do
    if [[ "$line" =~ "KEYBOARD_KEY" ]]; then
        key=$(echo "$line" | grep -oP '(?<=KEYBOARD_KEY\()[0-9]+' | head -1)
        break
    fi
done < <(sudo libinput debug-events --device /dev/input/event4)

# When input is recieved but is not the escape key
if [[ "$key" -ne "$ESCAPE_KEY" ]]; then
    killall swaylock
    swaylock -i "$MEME_FILE"
fi

rm $TEMP_FILE_PHOTO
