version: 2.0

jobs:
    build:
        docker:
            - image: circleci/python:latest
        steps:
            - checkout
            - run: sudo apt update && sudo apt install shellcheck -y
            - run: shellcheck pranklock
